// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcwvUf8CyH_TRZdQQtG0Nf6TJjZEvZn8w',
    appId: '1:409024656971:web:bbb0512e776b9b2d883fce',
    messagingSenderId: '409024656971',
    projectId: 'farmerhub-f180a',
    authDomain: 'farmerhub-f180a.firebaseapp.com',
    storageBucket: 'farmerhub-f180a.firebasestorage.app',
    measurementId: 'G-915RV3J2QJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo_dZzuexyecoE56BwAKgJw8k73J6pSrE',
    appId: '1:409024656971:android:2bfbff8e58e38d45883fce',
    messagingSenderId: '409024656971',
    projectId: 'farmerhub-f180a',
    storageBucket: 'farmerhub-f180a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcwvUf8CyH_TRZdQQtG0Nf6TJjZEvZn8w',
    appId: '1:409024656971:web:d1e18c2522640562883fce',
    messagingSenderId: '409024656971',
    projectId: 'farmerhub-f180a',
    authDomain: 'farmerhub-f180a.firebaseapp.com',
    storageBucket: 'farmerhub-f180a.firebasestorage.app',
    measurementId: 'G-Z7N7C02JGB',
  );
}
